### ISSUE TITLE
Question about path CV

### ISSUE THREAD

**Issue by gitkol** [RedesignScience/cvpack#92]
Hi, I have been using path CV extensively with OpenMM-PLUMED, and got very excited to learn about your fantastic CV library that runs on the GPU. My understanding, though, is that your path CV defines the milestones in CV space. Do you have any suggestion how to use your library when the milestones are defined by intermediate structures between two conformations identified with their atomic coordinates as opposed to _s_ and _z_, which in this case would just be a trivial sequence of (1,0), (2,0), etc.?

Thank you very much!

Best regards,

   Istvan

**Comment by craabreu** [comment]
Thank you for the question and the feedback.

A new path-CV class is necessary to use the library in the way you mentioned. It has to accept reference structures as milestones and use RMSD to measure the distance between the current state and each milestone. It would be identical to `PathInCVSpace` in all other features, which makes such implementation relatively simple.

I started PR #93 to implement this new class. It might be available in the next release version.

**Comment by craabreu** [comment]
It helps a lot! Thank you very much.

The latest CVPack version (v0.12.0) includes the new [PathInRMSDSpace](https://redesignscience.github.io/cvpack/latest/api/PathInRMSDSpace.html) class. It is already available for installation via `conda`/`mamba` or `pip`.

**Comment by gitkol** [comment]
Amazing, thank you Charlles! I’ll install and try it with an example from
my OpenMM-PLUMED runs.

Best,

   István

**Comment by craabreu** [comment]
I'm closing this issue. Please feel free to either reopen it or create a new one.
